Repository OCA/l10n-mexico, pull requests merged in 2025-03, with the labels that each got.

#58 [ADD] currency_rate_update_banxico: add Bank of Mexico as currency provider
  currency_rate_update_banxico/README.rst
  currency_rate_update_banxico/__init__.py
  currency_rate_update_banxico/__manifest__.py
  currency_rate_update_banxico/models/__init__.py
  currency_rate_update_banxico/models/res_currency_rate_provider_banxico.py
  currency_rate_update_banxico/pyproject.toml
  currency_rate_update_banxico/readme/CONFIGURE.md
  currency_rate_update_banxico/readme/CONTRIBUTORS.md
  currency_rate_update_banxico/readme/DESCRIPTION.md
  currency_rate_update_banxico/static/description/index.html
  currency_rate_update_banxico/tests/__init__.py
  currency_rate_update_banxico/tests/test_currency_rate_update_banxico.py
  currency_rate_update_banxico/views/res_currency_rate_provider_views.xml
  requirements.txt
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#65 [15.0] ocabot update dotfiles
  l10n_mx_cfdi/README.rst
  l10n_mx_cfdi/readme/USAGE.rst
  l10n_mx_cfdi/static/description/index.html
Labels: bug, needs review

#64 [IMP] l10n_mx_cfdi: Update CONFIGURE.md
  l10n_mx_cfdi/readme/CONFIGURE.md
Labels: enhancement, needs review, approved, ready to merge
