Repository OCA/l10n-mexico, pull requests merged in 2025-01, with the labels that each got.

#55 [FIX] l10n_mx_res_partner_csf
  l10n_mx_res_partner_csf/README.rst
  l10n_mx_res_partner_csf/readme/INSTALL.md
  l10n_mx_res_partner_csf/security/ir.model.access.csv
  l10n_mx_res_partner_csf/static/description/index.html
  l10n_mx_res_partner_csf/wizard/import_csf.py
Labels: bug, needs review, bot is merging ⏳

#46 [17.0][MIG] l10n_mx_cfdi_account
  l10n_mx_catalogs/__manifest__.py
  l10n_mx_cfdi/__manifest__.py
  l10n_mx_cfdi/security/ir.model.access.csv
  l10n_mx_cfdi/views/cfdi_documents_issued.xml
  l10n_mx_cfdi/views/cfdi_menu.xml
  l10n_mx_cfdi/views/product_template.xml
  l10n_mx_cfdi/views/res_partner.xml
  l10n_mx_cfdi_account/README.rst
  l10n_mx_cfdi_account/__init__.py
  l10n_mx_cfdi_account/__manifest__.py
  l10n_mx_cfdi_account/i18n/l10n_mx_cfdi.pot
  l10n_mx_cfdi_account/models/__init__.py
  l10n_mx_cfdi_account/models/account_move.py
  l10n_mx_cfdi_account/models/account_move_line.py
  l10n_mx_cfdi_account/models/account_move_reversal.py
  l10n_mx_cfdi_account/models/account_partial_reconcile.py
  l10n_mx_cfdi_account/models/account_payment.py
  l10n_mx_cfdi_account/models/account_payment_register.py
  l10n_mx_cfdi_account/models/account_tax.py
  l10n_mx_cfdi_account/models/cfdi_document.py
  l10n_mx_cfdi_account/models/res_config_settings.py
  l10n_mx_cfdi_account/pyproject.toml
  l10n_mx_cfdi_account/readme/CONFIGURE.md
  l10n_mx_cfdi_account/readme/CONTRIBUTORS.md
  l10n_mx_cfdi_account/readme/DESCRIPTION.md
  l10n_mx_cfdi_account/readme/INSTALL.md
  l10n_mx_cfdi_account/readme/ROADMAP.md
  l10n_mx_cfdi_account/readme/USAGE.md
  l10n_mx_cfdi_account/reports/report_external_layouts.xml
  l10n_mx_cfdi_account/reports/report_invoice.xml
  l10n_mx_cfdi_account/reports/report_payment.xml
  l10n_mx_cfdi_account/security/ir.model.access.csv
  l10n_mx_cfdi_account/static/description/icon.png
  l10n_mx_cfdi_account/static/description/icon.svg
  l10n_mx_cfdi_account/static/description/index.html
  l10n_mx_cfdi_account/tests/__init__.py
  l10n_mx_cfdi_account/tests/test_account_move.py
  l10n_mx_cfdi_account/tests/test_account_move_line.py
  l10n_mx_cfdi_account/tests/test_account_payment.py
  l10n_mx_cfdi_account/tests/test_account_tax.py
  l10n_mx_cfdi_account/views/account_move.xml
  l10n_mx_cfdi_account/views/account_payment.xml
  l10n_mx_cfdi_account/views/account_payment_register.xml
  l10n_mx_cfdi_account/views/res_config_settings.xml
  l10n_mx_cfdi_account/wizards/__init__.py
  l10n_mx_cfdi_account/wizards/account_invoice_send_views.xml
  l10n_mx_cfdi_account/wizards/create_cfdi_publico_en_general.py
  l10n_mx_cfdi_account/wizards/create_cfdi_publico_en_general.xml
  l10n_mx_cfdi_account/wizards/document_cancel.py
  l10n_mx_cfdi_account/wizards/document_cancel_form.xml
  l10n_mx_cfdi_account/wizards/download_cfdi_files.py
  l10n_mx_cfdi_account/wizards/download_cfdi_files_wizard.xml
Labels: enhancement, needs fixing, needs review, bot is merging ⏳

#56 [FIX] l10n_mx_cfdi_account: INSTALL.md
  l10n_mx_cfdi_account/readme/INSTALL.md
Labels: bug, needs review, bot is merging ⏳

#59 [FIX] l10n_mx_cfdi_account
  l10n_mx_cfdi_account/models/account_move.py
Labels: bug, needs review, approved, bot is merging ⏳
